name: Prettify

on:
  pull_request:
    branches: [ main ]
  push:
    branches:
      - main

jobs:
  prettier:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          ref: ${{ github.head_ref }}
          fetch-depth: 0

      - name: Prettify code
        uses: creyD/prettier_action@v4.3
        with:
          prettier_version: 2.8.4
          prettier_options: --write **/*.{ts,tsx,json}
          only_changed: True
          same_commit: True
